fix(reqs): limit urllib3 version
urllib3 is directly required by the lib/edgegrid.py module
and has recently been released in its 2.x version line, introducing
some breaking changes causing errors in recent installations, e.g.

```
TypeError: Retry.__init__() got an unexpected keyword argument 'method whitelist'
```